"""Reconcile migration history with the current models.

Earlier alpha builds bootstrapped schema via ``create_all`` + a hand-maintained repair
function rather than Alembic, so the migration chain drifted from ``Base.metadata``:
the removed ``direction_profiles`` table was never dropped, many foreign-key columns that
models declare NOT NULL were still nullable, and several indexes had stale names/uniqueness.
This migration closes that drift honestly so ``test_migrations.py`` passes without weakening
the comparison. Autogenerated via ``alembic revision --autogenerate`` and reviewed.
"""

from alembic import op
import sqlalchemy as sa

revision = "0025_schema_reconciliation"
down_revision = "0024_segment_render_uniqueness"
branch_labels = None
depends_on = None

# No `_repair_sqlite_schema_drift` mirror needed: legacy DBs bootstrap via `create_all`,
# which already matches current models, so these NOT NULL tightenings must not be repaired.


def upgrade() -> None:
    with op.batch_alter_table("direction_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_direction_scope"))
    op.drop_table("direction_profiles")

    with op.batch_alter_table("ambience_assets", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_ambience_assets_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("ambience_cues", schema=None) as batch_op:
        batch_op.alter_column("scene_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_ambience_cues_scene_id"), ["scene_id"], unique=False
        )

    with op.batch_alter_table("ambience_profiles", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_ambience_profiles_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("chapter_renders", schema=None) as batch_op:
        batch_op.alter_column("chapter_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=32), nullable=False)
        batch_op.alter_column("speech_path", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("manifest_path", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("duration_ms", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_chapter_renders_chapter_id"), ["chapter_id"], unique=False
        )

    with op.batch_alter_table("character_voice_assignments", schema=None) as batch_op:
        batch_op.alter_column("character_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.alter_column(
            "voice_profile_id", existing_type=sa.VARCHAR(length=64), nullable=False
        )

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_characters_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column("issue_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(batch_op.f("ix_comments_issue_id"), ["issue_id"], unique=False)

    with op.batch_alter_table("export_packages", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_export_packages_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(batch_op.f("ix_issues_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_issues_segment_id"), ["segment_id"], unique=False)

    with op.batch_alter_table("model_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_installations_model_key"))
        batch_op.create_index(
            batch_op.f("ix_model_installations_model_key"), ["model_key"], unique=True
        )

    with op.batch_alter_table("patch_attempts", schema=None) as batch_op:
        batch_op.alter_column("segment_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.alter_column("new_render_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.alter_column(
            "chapter_render_id", existing_type=sa.VARCHAR(length=64), nullable=False
        )
        batch_op.create_index(
            batch_op.f("ix_patch_attempts_issue_id"), ["issue_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_patch_attempts_segment_id"), ["segment_id"], unique=False
        )

    with op.batch_alter_table("pronunciation_entries", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_pronunciation_entries_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("readiness_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_readiness_reports_chapter"))
        batch_op.drop_index(batch_op.f("ix_readiness_reports_project"))
        batch_op.create_index(
            batch_op.f("ix_readiness_reports_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_readiness_reports_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("render_queue_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_queue_chapter"))
        batch_op.drop_index(batch_op.f("ix_render_queue_job"))
        batch_op.drop_index(batch_op.f("ix_render_queue_project"))
        batch_op.drop_index(batch_op.f("ix_render_queue_segment"))
        batch_op.create_index(
            batch_op.f("ix_render_queue_items_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_render_queue_items_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_render_queue_items_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_render_queue_items_segment_id"), ["segment_id"], unique=False
        )

    with op.batch_alter_table("segment_directions", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)

    with op.batch_alter_table("segment_renders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_renders_key"))
        batch_op.create_index(
            batch_op.f("ix_segment_renders_segment_id"), ["segment_id"], unique=False
        )

    with op.batch_alter_table("speaker_attributions", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.alter_column("segment_id", existing_type=sa.VARCHAR(length=64), nullable=False)

    with op.batch_alter_table("voice_profiles", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_voice_profiles_project_id"), ["project_id"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("voice_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_profiles_project_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("speaker_attributions", schema=None) as batch_op:
        batch_op.alter_column("segment_id", existing_type=sa.VARCHAR(length=64), nullable=True)
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("segment_renders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_renders_segment_id"))
        batch_op.create_index(
            batch_op.f("ix_segment_renders_key"), ["segment_id", "render_key"], unique=False
        )

    with op.batch_alter_table("segment_directions", schema=None) as batch_op:
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("render_queue_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_queue_items_segment_id"))
        batch_op.drop_index(batch_op.f("ix_render_queue_items_project_id"))
        batch_op.drop_index(batch_op.f("ix_render_queue_items_job_id"))
        batch_op.drop_index(batch_op.f("ix_render_queue_items_chapter_id"))
        batch_op.create_index(batch_op.f("ix_render_queue_segment"), ["segment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_render_queue_project"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_render_queue_job"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_render_queue_chapter"), ["chapter_id"], unique=False)

    with op.batch_alter_table("readiness_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_readiness_reports_project_id"))
        batch_op.drop_index(batch_op.f("ix_readiness_reports_chapter_id"))
        batch_op.create_index(batch_op.f("ix_readiness_reports_project"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_readiness_reports_chapter"), ["chapter_id"], unique=False)

    with op.batch_alter_table("pronunciation_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pronunciation_entries_project_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("patch_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patch_attempts_segment_id"))
        batch_op.drop_index(batch_op.f("ix_patch_attempts_issue_id"))
        batch_op.alter_column("chapter_render_id", existing_type=sa.VARCHAR(length=64), nullable=True)
        batch_op.alter_column("new_render_id", existing_type=sa.VARCHAR(length=64), nullable=True)
        batch_op.alter_column("segment_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("model_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_installations_model_key"))
        batch_op.create_index(
            batch_op.f("ix_model_installations_model_key"), ["model_key"], unique=False
        )

    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issues_segment_id"))
        batch_op.drop_index(batch_op.f("ix_issues_project_id"))
        batch_op.drop_index(batch_op.f("ix_issues_chapter_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("export_packages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_export_packages_project_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_issue_id"))
        batch_op.alter_column("issue_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_project_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("character_voice_assignments", schema=None) as batch_op:
        batch_op.alter_column("voice_profile_id", existing_type=sa.VARCHAR(length=64), nullable=True)
        batch_op.alter_column("character_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("chapter_renders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapter_renders_chapter_id"))
        batch_op.alter_column("duration_ms", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("manifest_path", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("speech_path", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=32), nullable=True)
        batch_op.alter_column("chapter_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("ambience_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ambience_profiles_project_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("ambience_cues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ambience_cues_scene_id"))
        batch_op.alter_column("scene_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    with op.batch_alter_table("ambience_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ambience_assets_project_id"))
        batch_op.alter_column("project_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    op.create_table(
        "direction_profiles",
        sa.Column("id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("scope_type", sa.VARCHAR(length=32), nullable=False),
        sa.Column("scope_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("payload_json", sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("direction_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_direction_scope"), ["scope_type", "scope_id"], unique=True
        )
