export type Project = { id: string; title: string; author: string | null; status: string; artifactPath: string; createdAt: string };
export type Job = { id: string; status: "queued" | "running" | "succeeded" | "failed" | "cancelled"; errorMessage?: string | null; progress: Record<string, unknown> };
export type ParserWarning = { severity: string; sourceRange?: string | null; message: string; suggestedAction?: string | null };
export type SourceDocument = { id: string; projectId: string; originalFilename: string; status: string; parserVersion: string; canonicalPath?: string | null; manifestPath?: string | null; preview?: string | null; warnings: ParserWarning[] };
export type SourcePage = { id: string; sourceDocumentId: string; pageNumber: number; imagePath?: string | null; imageUrl?: string | null; embeddedTextPath?: string | null; selectedTextPath?: string | null; extractionMethod: string; confidence: number; warnings: ParserWarning[]; preview?: string | null };
export type CleaningRun = { id: string; sourceDocumentId: string; status: string; manifestPath?: string | null; startedAt: string; completedAt?: string | null; errorMessage?: string | null };
export type TextCleanlinessIssue = { id: string; sourceDocumentId: string; canonicalSpanStart: number; canonicalSpanEnd: number; issueType: string; severity: string; suggestedFix?: string | null; confidence: number; status: string; resolvedByUser: boolean };
export type StructureParserWarning = { id: string; projectId: string; sourceDocumentId?: string | null; scopeType: string; scopeId: string; severity: string; message: string; evidence: Record<string, unknown>; confidence: number; resolved: boolean; createdAt: string };
export type Chapter = { id: string; title?: string | null; status: string; confidence: number; parserEvidence?: Record<string, unknown>; userLocked: boolean; lockReason?: string | null };
export type Scene = { id: string; status: string; confidence: number; parserEvidence?: Record<string, unknown>; userLocked: boolean; lockReason?: string | null };
export type Segment = { id: string; sceneId: string; textContent: string; revision: number; status: string; speakerCandidate?: string | null; segmentType: string; parserEvidence?: Record<string, unknown>; userLocked: boolean; lockReason?: string | null };
export type SpeakerAttribution = { id: string; projectId: string; segmentId: string; characterId?: string | null; speakerName?: string | null; method: string; evidence: Record<string, unknown>; confidence: number; status: string; userLocked: boolean; voiceProfileId?: string | null; createdAt: string; updatedAt: string };
export type Direction = { scopeType: string; scopeId: string; pace: number; intensity: number; tone: string; emotion: string; pauseBeforeMs: number; pauseAfterMs: number; stylePrompt?: string | null; emphasis: boolean; whisper: boolean; noSfx: boolean };
export type SegmentDirection = { segmentId: string; projectId: string; direction: Direction; source: string; userLocked: boolean; directionFingerprint: string; createdAt: string; updatedAt: string };
export type TtsSettings = { provider: "mock" | "kokoro"; setupMode?: "managed_onnx" | "custom_adapter" | null; executable?: string | null; runtimeRoot?: string | null; pythonPath?: string | null; modelPath?: string | null; voicesDataPath?: string | null; voiceRegistryPath?: string | null; ready: boolean; message?: string | null; availableVoices: string[] };
export type KokoroSetupStep = { phase: string; label: string; status: string; message?: string | null };
export type KokoroSetupStatus = { platform: string; state: "not_started" | "incomplete" | "failed" | "ready" | "active"; setupMode: "managed_onnx"; runtimeRoot: string; pythonPath: string; executable: string; modelPath: string; voicesDataPath: string; voiceRegistryPath: string; ready: boolean; message?: string | null; nextAction: string; availableVoices: string[]; steps: KokoroSetupStep[] };
export type LocalAiCatalogItem = { modelKey: string; displayName: string; capability: string; provider: string; installType: string; required: boolean; sizeMb?: number | null; licenseSummary?: string | null; licenseNote?: string | null; description?: string | null; status: string; health: string; installPath?: string | null; lastVerifiedAt?: string | null };
export type LocalAiInstallation = { id: string; modelKey: string; displayName: string; capability: string; provider: string; version?: string | null; installPath?: string | null; status: string; installedAt?: string | null; lastVerifiedAt?: string | null; sizeBytes?: number | null; licenseSummary?: string | null; errorMessage?: string | null };
export type LocalAiInstallJob = { id: string; jobId: string; modelKey: string; status: string; progressPercent: number; currentStep?: string | null; logsPath?: string | null; startedAt?: string | null; completedAt?: string | null; errorMessage?: string | null };
export type VoiceProfile = { id: string; projectId: string; name: string; backend: string; providerVoiceId: string; stylePrompt?: string | null };
export type ProductionSettings = { projectId: string; narratorVoiceProfileId?: string | null; defaultDirection?: Direction | null };
export type SegmentOverride = { segmentId: string; voiceProfileId?: string | null; direction?: Direction | null };
export type SegmentRender = { id: string; segmentId: string; status: string; audioPath: string; audioUrl?: string | null; durationMs: number; parentRenderId?: string | null };
export type ChapterRender = { id: string; chapterId: string; status: string; speechPath: string; audioUrl?: string | null; durationMs: number; renderMode: string };
export type ProductionStatus = { chapterId: string; ready: boolean; reason?: string | null; totalSegments: number; currentSegments: number; activeRender?: ChapterRender | null };
export type Issue = { id: string; projectId: string; chapterId?: string | null; segmentId?: string | null; severity: string; category: string; title: string; description: string; status: string };
export type Comment = { id: string; issueId: string; body: string; author: string; createdAt: string };
export type ExportPackage = { id: string; projectId: string; format: string; status: string; outputPath: string; manifestPath: string; archivePath?: string | null; downloadUrl?: string | null };
export type Character = {
  id: string;
  projectId: string;
  displayName: string;
  canonicalName?: string | null;
  aliases: string[];
  traits: string[];
  firstSeenSourceId?: string | null;
  firstSeenChapterId?: string | null;
  firstSeenSegmentId?: string | null;
  roleType: string;
  confidence: number;
  notes?: string | null;
  mergeHistory: Record<string, unknown>[];
  splitHistory: Record<string, unknown>[];
  userLocked: boolean;
  lockReason?: string | null;
  mergedIntoCharacterId?: string | null;
  voiceProfileId?: string | null;
};
export type Pronunciation = { id: string; term: string; phonetic?: string | null; replacementText?: string | null };

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export const assetUrl = (path?: string | null) => path ? `${apiUrl}${path}` : undefined;

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const headers = options?.body instanceof FormData ? options?.headers : { "Content-Type": "application/json", ...options?.headers };
  const response = await fetch(`${apiUrl}${path}`, { ...options, headers });
  if (!response.ok) {
    const detail = await response.json().catch(() => null) as { detail?: string } | null;
    throw new Error(detail?.detail ?? "The local studio could not complete that request.");
  }
  if (response.status === 204) return undefined as T;
  return response.json() as Promise<T>;
}
const json = (method: string, body?: object): RequestInit => ({ method, body: body ? JSON.stringify(body) : undefined });

export const listProjects = () => request<Project[]>("/api/v1/projects");
export const createProject = (payload: { title: string; author?: string; rightsStatus: "declared" }) => request<Project>("/api/v1/projects", json("POST", payload));
export const getJob = (id: string) => request<Job>(`/api/v1/jobs/${id}`);
export const getSource = (projectId: string) => request<SourceDocument>(`/api/v1/projects/${projectId}/source`);
export const getSourceById = (sourceId: string) => request<SourceDocument>(`/api/v1/sources/${sourceId}`);
export const listSourcePages = (sourceId: string) => request<SourcePage[]>(`/api/v1/sources/${sourceId}/pages`);
export const listCleaningRuns = (sourceId: string) => request<CleaningRun[]>(`/api/v1/sources/${sourceId}/cleaning-runs`);
export const listCleaningIssues = (sourceId: string) => request<TextCleanlinessIssue[]>(`/api/v1/sources/${sourceId}/cleaning-issues`);
export const updateCleaningIssue = (issueId: string, payload: { status?: string; resolvedByUser?: boolean }) => request<TextCleanlinessIssue>(`/api/v1/cleaning-issues/${issueId}`, json("PATCH", payload));
export async function importSource(projectId: string, file: File) { const form = new FormData(); form.set("file", file); form.set("rightsAcknowledged", "true"); return request<Job>(`/api/v1/projects/${projectId}/source/import`, { method: "POST", body: form }); }
export const reparseSource = (projectId: string) => request<Job>(`/api/v1/projects/${projectId}/source/reparse`, json("POST", { parserVersion: "ingestion-0.1.0" }));
export const extractStructure = (projectId: string) => request<Job>(`/api/v1/projects/${projectId}/structure/extract`, json("POST", { maxSegmentChars: 600 }));
export const listChapters = (projectId: string) => request<Chapter[]>(`/api/v1/projects/${projectId}/chapters`);
export const listStructureWarnings = (projectId: string) => request<StructureParserWarning[]>(`/api/v1/projects/${projectId}/structure-warnings`);
export const updateChapter = (chapterId: string, payload: { title?: string | null; status?: string | null }) => request<Chapter>(`/api/v1/chapters/${chapterId}`, json("PATCH", payload));
export const listScenes = (chapterId: string) => request<Scene[]>(`/api/v1/chapters/${chapterId}/scenes`);
export const updateScene = (sceneId: string, payload: { status?: string | null }) => request<Scene>(`/api/v1/scenes/${sceneId}`, json("PATCH", payload));
export const listSegments = (sceneId: string) => request<Segment[]>(`/api/v1/scenes/${sceneId}/segments`);
export const updateSegment = (id: string, textContent: string) => request<Segment>(`/api/v1/segments/${id}`, json("PATCH", { textContent }));
export const setStructureLock = (scopeType: "chapter" | "scene" | "segment", scopeId: string, payload: { locked: boolean; reason?: string | null }) => request<Chapter | Scene | Segment>(`/api/v1/structure-locks/${scopeType}/${scopeId}`, json("PUT", payload));
export const splitSegment = (id: string, splitOffset: number) => request<Segment>(`/api/v1/segments/${id}/split`, json("POST", { splitOffset }));
export const mergeSegment = (id: string, nextSegmentId: string) => request<Segment>(`/api/v1/segments/${id}/merge`, json("POST", { nextSegmentId }));
export const listSegmentDirections = (projectId: string) => request<SegmentDirection[]>(`/api/v1/projects/${projectId}/segment-directions`);
export const getSegmentDirection = (projectId: string, segmentId: string) => request<SegmentDirection>(`/api/v1/projects/${projectId}/segments/${segmentId}/direction`);
export const saveSegmentDirection = (projectId: string, segmentId: string, payload: { direction: Direction; userLocked?: boolean }) => request<SegmentDirection>(`/api/v1/projects/${projectId}/segments/${segmentId}/direction`, json("PUT", payload));
export const inferSegmentDirections = (projectId: string) => request<Job>(`/api/v1/projects/${projectId}/directions/infer`, json("POST", {}));
export const listSpeakerAttributions = (projectId: string, status?: string) => request<SpeakerAttribution[]>(`/api/v1/projects/${projectId}/speaker-attributions${status ? `?status=${encodeURIComponent(status)}` : ""}`);
export const runSpeakerAttribution = (projectId: string, payload: { useLocalLlm?: boolean; model?: string } = {}) => request<Job>(`/api/v1/projects/${projectId}/speaker-attributions/run`, json("POST", payload));
export const updateSpeakerAttribution = (attributionId: string, payload: { characterId?: string | null; speakerName?: string | null; status?: string; userLocked?: boolean }) => request<SpeakerAttribution>(`/api/v1/speaker-attributions/${attributionId}`, json("PATCH", payload));

export const getTtsSettings = () => request<TtsSettings>("/api/v1/settings/tts");
export const saveTtsSettings = (payload: Omit<TtsSettings, "ready" | "message" | "availableVoices">) => request<TtsSettings>("/api/v1/settings/tts", json("PUT", payload));
export const testTtsSettings = () => request<TtsSettings>("/api/v1/settings/tts/test", json("POST", {}));
export const getKokoroSetup = () => request<KokoroSetupStatus>("/api/v1/settings/tts/kokoro/setup");
export const installKokoroSetup = (payload: { confirmNetworkDownload: boolean; confirmThirdPartyLicense: boolean; repair?: boolean }) => request<Job>("/api/v1/settings/tts/kokoro/setup/install", json("POST", payload));
export const listLocalAiCatalog = () => request<LocalAiCatalogItem[]>("/api/v1/local-ai/catalog");
export const listLocalAiInstalled = () => request<LocalAiInstallation[]>("/api/v1/local-ai/installed");
export const getLocalAiInstallJob = (jobId: string) => request<LocalAiInstallJob>(`/api/v1/local-ai/jobs/${jobId}`);
export const installLocalAiModel = (modelKey: string, payload: { confirmNetworkDownload: boolean; confirmThirdPartyLicense: boolean; confirmSystemInstall: boolean; repair?: boolean }) => request<Job>(`/api/v1/local-ai/models/${modelKey}/install`, json("POST", payload));
export const verifyLocalAiModel = (modelKey: string) => request<LocalAiInstallation>(`/api/v1/local-ai/models/${modelKey}/verify`, json("POST"));
export const listVoices = (projectId: string) => request<VoiceProfile[]>(`/api/v1/projects/${projectId}/voices`);
export const createVoice = (projectId: string, payload: { name: string; backend: string; providerVoiceId: string; stylePrompt?: string }) => request<VoiceProfile>(`/api/v1/projects/${projectId}/voices`, json("POST", payload));
export const deleteVoice = (voiceId: string) => request<void>(`/api/v1/voices/${voiceId}`, { method: "DELETE" });
export const previewVoice = (projectId: string, voiceProfileId: string, direction: Direction) => request<{ assetPath: string; audioUrl?: string }>(`/api/v1/projects/${projectId}/voices/preview`, json("POST", { text: "This is a local Echodraft voice preview.", voiceProfileId, direction }));
export const listCharacters = (projectId: string) => request<Character[]>(`/api/v1/projects/${projectId}/characters`);
export const createCharacter = (projectId: string, payload: string | { displayName: string; canonicalName?: string; aliases?: string[]; traits?: string[]; roleType?: string; notes?: string }) => request<Character>(`/api/v1/projects/${projectId}/characters`, json("POST", typeof payload === "string" ? { displayName: payload } : payload));
export const updateCharacter = (characterId: string, payload: Partial<Pick<Character, "displayName" | "canonicalName" | "aliases" | "traits" | "roleType" | "confidence" | "notes" | "userLocked" | "lockReason" | "voiceProfileId">>) => request<Character>(`/api/v1/characters/${characterId}`, json("PATCH", payload));
export const mergeCharacter = (targetCharacterId: string, sourceCharacterId: string, reason?: string) => request<Character>(`/api/v1/characters/${targetCharacterId}/merge`, json("POST", { sourceCharacterId, reason }));
export const splitCharacter = (characterId: string, payload: { displayName: string; aliases?: string[]; traits?: string[]; reason?: string }) => request<Character>(`/api/v1/characters/${characterId}/split`, json("POST", payload));
export const listPronunciations = (projectId: string) => request<Pronunciation[]>(`/api/v1/projects/${projectId}/pronunciations`);
export const createPronunciation = (projectId: string, term: string, replacementText?: string) => request<Pronunciation>(`/api/v1/projects/${projectId}/pronunciations`, json("POST", { term, replacementText }));
export const getProductionSettings = (projectId: string) => request<ProductionSettings>(`/api/v1/projects/${projectId}/production-settings`);
export const saveProductionSettings = (projectId: string, payload: { narratorVoiceProfileId?: string | null; defaultDirection?: Direction | null }) => request<ProductionSettings>(`/api/v1/projects/${projectId}/production-settings`, json("PUT", payload));
export const getSegmentOverride = (projectId: string, segmentId: string) => request<SegmentOverride>(`/api/v1/projects/${projectId}/segments/${segmentId}/production-override`);
export const saveSegmentOverride = (projectId: string, segmentId: string, payload: { voiceProfileId?: string | null; direction?: Direction | null }) => request<SegmentOverride>(`/api/v1/projects/${projectId}/segments/${segmentId}/production-override`, json("PUT", payload));
export const getProductionStatus = (projectId: string, chapterId: string) => request<ProductionStatus>(`/api/v1/projects/${projectId}/chapters/${chapterId}/production-status`);
export const produceChapter = (projectId: string, chapterId: string, force = false) => request<Job>(`/api/v1/projects/${projectId}/chapters/${chapterId}/produce?force=${force}`, json("POST"));
export const listChapterRenders = (projectId: string, chapterId: string) => request<ChapterRender[]>(`/api/v1/projects/${projectId}/chapters/${chapterId}/renders`);
export const listIssues = (projectId: string) => request<Issue[]>(`/api/v1/projects/${projectId}/issues`);
export const updateIssue = (issueId: string, payload: { status?: string; severity?: string }) => request<Issue>(`/api/v1/issues/${issueId}`, json("PATCH", payload));
export const listComments = (issueId: string) => request<Comment[]>(`/api/v1/issues/${issueId}/comments`);
export const addComment = (issueId: string, body: string) => request<Comment>(`/api/v1/issues/${issueId}/comments`, json("POST", { body }));
export const patchSegment = (projectId: string, segmentId: string, payload: { textContent?: string; issueId?: string; voiceProfileId: string; direction: Direction }) => request<unknown>(`/api/v1/projects/${projectId}/segments/${segmentId}/patch`, json("POST", payload));
export const createExport = (projectId: string, format: "wav" | "mp3", chapterIds: string[]) => request<ExportPackage>(`/api/v1/projects/${projectId}/exports`, json("POST", { format, chapterIds }));
export const listExports = (projectId: string) => request<ExportPackage[]>(`/api/v1/projects/${projectId}/exports`);
